# Generated by Django 5.0.7 on 2024-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
